<a href="https://colab.research.google.com/github/KhadijaBENMESSAOUD/NLP-with-sickit-learn/blob/main/1%5D_NLP_spam_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import pandas as pd


In [57]:
#Concatenate the five review files
df= pd.concat([
    pd.read_csv('Youtube01-Psy.csv'),
    pd.read_csv('Youtube02-KatyPerry.csv'),
    pd.read_csv('Youtube03-LMFAO.csv'),
    pd.read_csv('Youtube04-Eminem.csv'),
    pd.read_csv('Youtube05-Shakira.csv')
])
df

COMMENT_ID                AUTHOR  \
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU             Julius NM   
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A           adam riyati   
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8      Evgeny Murashkin   
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04       ElNino Melendez   
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw                GsMega   
..                                           ...                   ...   
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA          Katie Mettam   
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  Sabina Pearson-Smith   
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs         jeffrey jules   
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0        Aishlin Maciel   
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA           Latin Bosch   

                           DATE  \
0           2013-11-07T06:20:48   
1           2013-11-07T12:37:15   
2           2013-11-08T17:34:21   
3           2013-11-09T08:28:43   
4           2013-11-10T16:05:38   
..                          ...   
365  2013-07-13T13:27:39.441000   
366  2013-07-13T13:14:30.021000   
367  2013-07-13T12:09:31.188000   
368  2013-07-13T11:17:52.308000   
369  2013-07-12T22:33:27.916000   

                                               CONTENT  CLASS  
0    Huh, anyway check out this you[tube] channel: ...      1  
1    Hey guys check out my new channel and our firs...      1  
2               just for test I have to say murdev.com      1  
3     me shaking my sexy ass on my channel enjoy ^_^       1  
4              watch?v=vtaRGgvGtWQ   Check this out .      1  
..                                                 ...    ...  
365  I love this song because we sing it at Camp al...      0  
366  I love this song for two reasons: 1.it is abou...      0  
367                                                wow      0  
368                            Shakira u are so wiredo      0  
369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

Show informations of the dataframe

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1956 entries, 0 to 369
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  1956 non-null   object
 1   AUTHOR      1956 non-null   object
 2   DATE        1711 non-null   object
 3   CONTENT     1956 non-null   object
 4   CLASS       1956 non-null   int64 
dtypes: int64(1), object(4)
memory usage: 91.7+ KB


Show comment of the fourth line

In [59]:
df.CONTENT.iloc[3]

'me shaking my sexy ass on my channel enjoy ^_^ \ufeff'

Show Spam and No spam proportion

In [60]:
df.CLASS.value_counts(normalize=True)
#Normalize='true' convert values into percentage

1    0.513804
0    0.486196
Name: CLASS, dtype: float64

Divide our dataset into train set and test set

In [61]:
#Train/test Split
from sklearn.model_selection import train_test_split
seed=123
X_train,X_test,y_train,y_test=train_test_split(df['CONTENT'],df['CLASS'],test_size=0.2, random_state=seed)

X_train and y_train have same dimensions

In [62]:
X_train.shape

(1564,)

In [63]:
y_train.shape

(1564,)

20% of dataset is the data number of test size (test_size=0.2)

In [64]:
X_test.shape

(392,)

In [65]:
X_train

38     Love this song! My soccer team made a cd for o...
72                                      Sub my channel!
356    I WILL NEVER FORGET THIS SONG IN MY LIFE LIKE ...
126                   Love the way you lie - Driveshaft
340    *****PLEASE READ*****  Hey everyone! I&#39;m a...
                             ...                        
422    check it out free stuff for watching videos an...
208    HEY GUYS!!! ❤❤❤❤❤❤❤  BEFORE YOU IGNORE ME, PLE...
268                   Hello. İ am from Azerbaijan<br />
251                                   dude check out psy
396    I KNOW YOU MAY NOT WANT TO READ THIS BUT pleas...
Name: CONTENT, Length: 1564, dtype: object

ML algorithm dont accept text format so we have to transform **X_train** into numerical matrix by using back of word for example

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
X_train_vec=vectorizer.fit_transform(X_train)
X_test_vec=vectorizer.transform(X_test)

In [67]:
X_train_vec

<1564x3846 sparse matrix of type '<class 'numpy.int64'>'
	with 20361 stored elements in Compressed Sparse Row format>

In [68]:
vectorizer.get_feature_names_out()

array(['00', '000', '002', ..., 'ｔｈｉｓ', 'ｕｓｒ', 'ｗｗｗ'], dtype=object)

In [69]:
len(vectorizer.get_feature_names_out())

3846

We will use Random Forest

In [70]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=seed)
rf_fitted=rf.fit(X_train_vec,y_train)

check train score

In [71]:
rf_fitted.score(X_test_vec,y_test)

0.9617346938775511

Show classification Report

In [72]:
from sklearn.metrics import classification_report
print(classification_report(y_test,rf_fitted.predict(X_test_vec)))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96       187
           1       0.98      0.95      0.96       205

    accuracy                           0.96       392
   macro avg       0.96      0.96      0.96       392
weighted avg       0.96      0.96      0.96       392



Cross validation to ensure the model performance :



In [73]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(rf,X_train_vec,y_train,cv=3) #"cv=3" because we have less than 10k samples
scores

array([0.95402299, 0.95393474, 0.94241843])

The mean score:

In [74]:
scores.mean()

0.9501253851641037

The median score

In [75]:
np.median(scores)

0.9539347408829175

CONCLUSION/Deduction

In [85]:
rf_fitted.predict(vectorizer.transform(['Join me on www for more fun'])) #Spam EXAMPLE

array([1])

In [77]:
rf_fitted.predict(vectorizer.transform(['I love Eminem'])) #No spam example

array([0])